# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('public', '公開中'), ('private', '非公開')], default='draft', max_length=8),
        ),
    ]
